#!/usr/bin/env bash
# A script that solves the FizzBuzz challenge for counting numbers, 1 - 100

for i in {1..100}; do
	if [ "$((i % 3))" -eq 0 ] && [ "$((i % 5))" -eq 0 ]; then
		echo "FizzBuzz"

	elif [ "$((i % 3))" -eq 0 ]; then
		echo "Fizz"

	elif [ "$((i % 5))" -eq 0 ]; then
		echo "Buzz"
	
	else
		echo "$i"
	fi

done
