#!/usr/bin/env bash
# A  script that prints "Best School" 10 times using the `while loop` and on the 9th iteration, displays "Hi" as well

i=0

while ((i  < 10)); do
	((i++))
	
	echo "Best School"

	if [ $i -eq 9 ]; then
		echo "Hi"
	fi

done
