#!/usr/bin/env bash
# A script that displays numbers from 1-20, bad luck from (china/japan/italy) on the 4th, 9th and 17th iterations respectively

i=1

while ((i  <= 20)); do
	
	echo "$i"

	case "$i" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac

	((i++))
done
